In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df =  pd.read_csv('newcsv.csv')

In [3]:
df.describe()

,Unnamed: 0,HolidayFlag,DayOfWeek,WeekOfYear,Day,Month,Year,PeriodOfDay,ForecastWindProduction,SystemLoadEA,SMPEA,ORKTemperature,ORKWindspeed,CO2Intensity,ActualWindProduction,SystemLoadEP2,SMPEP2
count,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000,38014.000000
mean,19006.500000,0.040406,2.997317,28.124586,15.739412,6.904246,2012.383859,23.501105,544.261451,4020.085019,62.720388,9.626369,19.211770,479.373040,520.762819,3785.973841,64.136823
std,10973.840903,0.196912,1.999959,15.587575,8.804247,3.573696,0.624956,13.853108,414.337377,860.454229,32.251486,4.422672,9.533594,85.346847,378.258096,843.247271,35.414105
min,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2011.000000,0.000000,0.680000,2183.940000,0.000000,-4.000000,0.000000,0.000000,1.000000,1809.960000,-47.740000
25%,9503.250000,0.000000,1.000000,15.000000,8.000000,4.000000,2012.000000,12.000000,189.700000,3281.220000,45.530000,7.000000,13.000000,421.110000,199.000000,3058.285000,45.780000
50%,19006.500000,0.000000,3.000000,29.000000,16.000000,7.000000,2012.000000,24.000000,442.050000,4103.495000,55.230000,9.000000,18.500000,480.290000,445.000000,3865.725000,55.550000
75%,28509.750000,0.000000,5.000000,43.000000,23.000000,10.000000,2013.000000,35.750000,839.430000,4638.487500,70.320000,13.000000,24.100000,537.475000,793.000000,4427.572500,72.107500
max,38013.000000,1.000000,6.000000,52.000000,31.000000,12.000000,2013.000000,47.000000,1680.000000,6492.910000,587.580000,25.000000,75.900000,842.880000,1769.000000,6309.750000,1000.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38014 entries, 0 to 38013
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              38014 non-null  int64
 1   Holiday                 1536 non-null   object
 2   HolidayFlag             38014 non-null  int64
 3   DayOfWeek               38014 non-null  int64
 4   WeekOfYear              38014 non-null  int64
 5   Day                     38014 non-null  int64
 6   Month                   38014 non-null  int64
 7   Year                    38014 non-null  int64
 8   PeriodOfDay             38014 non-null  int64
 9   ForecastWindProduction  38014 non-null  float64
 10  SystemLoadEA            38014 non-null  float64
 11  SMPEA                   38014 non-null  float64
 12  ORKTemperature          38014 non-null  float64
 13  ORKWindspeed            38014 non-null  float64
 14  CO2Intensity            38014 non-null  float64
 15  ActualWindProduction    38014 non-null  float64
 16  SystemLoadEP2           38014 non-null  float64
 17  SMPEP2                  38014 non-null  float64
dtypes: float64(9), int64(8), object(1)
memory usage: 5.2+ MB